[project]
name = "curtail"
version = "1.15.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.15.4",
]

[tool.ruff]
builtins = ["_"]
